# Generated by Django 6.1.1 on 2026-09-15 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_details', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active / Escrow Funded'), ('INSPECTION', 'Under Inspection'), ('LOGISTICS', 'In Transit'), ('COMPLETED', 'Completed / Funds Released'), ('DISPUTED', 'Dispute Raised'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_contracts', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector_contracts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('VEHICLE_CONDITION_MISMATCH', 'Vehicle Condition Mismatch'), ('UNDISCLOSED_DAMAGE', 'Undisclosed Damage'), ('LOGISTICS_DELAY_DAMAGE', 'Transit Damage / Failure'), ('DOCUMENTATION_ISSUE', 'Title / Documentation Issue'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open / Under Investigation'), ('IN_REVIEW', 'In Review by Arbiter'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('FULL_REFUND_BUYER', 'Full Refund to Buyer'), ('FULL_PAYOUT_SELLER', 'Full Payout to Seller'), ('PARTIAL_REFUND', 'Partial Refund / Split Settlement')], max_length=30, null=True)),
                ('buyer_refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seller_payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('arbiter_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='core.escrowcontract')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_condition', models.CharField(max_length=50)),
                ('odometer_reading', models.IntegerField(help_text='Current mileage verified during inspection')),
                ('notes', models.TextField(help_text='Detailed mechanics notes regarding engine, bodywork, and structural integrity')),
                ('recommendation', models.CharField(choices=[('PASS', 'Pass / Vehicle Approved'), ('FAIL', 'Fail / Significant Issues Detected'), ('CONDITIONAL', 'Conditional / Repairs Required')], default='PASS', max_length=20)),
                ('passed_inspection', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='core.escrowcontract')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Carrier Assigned'), ('PICKED_UP', 'Picked Up / In Transit'), ('DELIVERED', 'Delivered to Destination'), ('DELAYED', 'Transit Delayed')], default='ASSIGNED', max_length=20)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_booking', to='core.escrowcontract')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transmission', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='escrowcontract',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_contracts', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit / Escrow Lock'), ('PAYOUT', 'Payout Release'), ('REFUND', 'Dispute Refund')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.escrowcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
